-- H2-compatible schema for unit/integration tests.
-- Uses BIGINT AUTO_INCREMENT instead of BIGSERIAL (same semantics, broader compatibility).
DROP TABLE IF EXISTS messages;

CREATE TABLE messages (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id   VARCHAR(36)   NOT NULL,
    room_id      SMALLINT      NOT NULL,
    user_id      INT           NOT NULL,
    username     VARCHAR(20)   NOT NULL,
    message      TEXT          NOT NULL,
    message_type VARCHAR(8)    NOT NULL,
    server_id    VARCHAR(50),
    client_ip    VARCHAR(45),
    sent_at      BIGINT        NOT NULL,
    created_at   TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_message_id UNIQUE (message_id)
);
